BowlingLeague/Models/Bowler.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BowlingLeague.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerID { get; set; } // {get;} would be a read-only variable

        [Required(ErrorMessage = "Please enter a first name!")]
        public string BowlerFirstName { get; set; }

        public string BowlerMiddleInit { get; set; }

        [Required(ErrorMessage = "Please enter a last name!")]
        public string BowlerLastName { get; set; }

        [Required(ErrorMessage = "Please enter a address!")]
        public string BowlerAddress { get; set; }

        [Required(ErrorMessage = "Please enter a city!")]
        public string BowlerCity { get; set; }

        [Required(ErrorMessage = "Please enter a state!")]
        public string BowlerState { get; set; }

        [Required(ErrorMessage = "Please enter a zip!")]
        public string BowlerZip { get; set; }

        [Required(ErrorMessage = "Please enter a phone number!")]
        public string BowlerPhoneNumber { get; set; }

        //Foreign Key
        [Required(ErrorMessage = "Please select a team!")]
        public int TeamID { get; set; }
        public Team Team { get; set; }
    }
}

BowlingLeague/Models/BowlingLeagueDbContext.cs
using System;
using Microsoft.EntityFrameworkCore;

namespace BowlingLeague.Models
{
    public class BowlingLeagueDbContext : DbContext 
    {
        public BowlingLeagueDbContext(DbContextOptions<BowlingLeagueDbContext> options) : base(options)
        {

        }

        public DbSet<Bowler> Bowlers { get; set; }
        public DbSet<Team> Teams { get; set; }
    }
}

BowlingLeague/Models/EFBowlingLeagueRepository.cs
using System;
using System.Linq;

namespace BowlingLeague.Models
{
    public class EFBowlingLeagueRepository : IBowlingLeagueRepository
    {
        public BowlingLeagueDbContext _repo { get; set; }

        public EFBowlingLeagueRepository(BowlingLeagueDbContext temp)
        {
            _repo = temp;
        }

        public IQueryable<Bowler> Bowlers => _repo.Bowlers;

        public IQueryable<Team> Teams => _repo.Teams; 


        public void Save(Bowler b)
        {
            _repo.SaveChanges();
        }

        public void Add(Bowler b)
        {
            _repo.Add(b);
            _repo.SaveChanges();
        }

        public void Delete(Bowler b)
        {
            _repo.Remove(b);
            _repo.SaveChanges();
        }
    }
}

BowlingLeague/Models/IBowlingLeagueRepository.cs
using System;
using System.Linq;

namespace BowlingLeague.Models
{
    public interface IBowlingLeagueRepository
    {
        IQueryable<Bowler> Bowlers { get; }

        IQueryable<Team> Teams { get; }

        public void Save(Bowler b);

        public void Add(Bowler b);

        public void Delete(Bowler b);

    }
}

BowlingLeague/Models/Team.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BowlingLeague.Models
{
    public class Team
    {
        [Key]
        [Required]
        public int TeamID { get; set; }

        public string TeamName { get; set; }

        public int CaptainID { get; set; }
    }
}

BowlingLeague/Components/TeamsViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BowlingLeague.Models;

namespace BowlingLeague.Components
{
    public class TeamsViewComponent : ViewComponent
    {
        private IBowlingLeagueRepository repo { get; set; }

        public TeamsViewComponent(IBowlingLeagueRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedTeam = RouteData?.Values["team"];

            var teams = repo.Teams
                .Select(x => x.TeamName)
                .Distinct()
                .OrderBy(x => x);

            return View(teams);
        }
    }
}

BowlingLeague/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BowlingLeague.Models;
using Microsoft.EntityFrameworkCore;

namespace BowlingLeague.Controllers
{
    public class HomeController : Controller
    {
        //private BowlingLeagueDbContext _context { get; set; }

        private BowlingLeagueDbContext _repo { get; set; }

        //Constructor 
        //public HomeController(BowlingLeagueDbContext temp)
        //{
        //    _context = temp; 
        //}

        public HomeController(BowlingLeagueDbContext temp)
        {
            _repo = temp;
        }

        public IActionResult Index(string team)
        {
            var teams = _repo.Teams.ToList();

            var bowlers = _repo.Bowlers // if using repo method do _repo.Bowlers here, use _context if not 
                .Include(x => x.Team)
                //.FromSqlRaw("SELECT * FROM Bowlers") // can build the output with a sql statement
                .Where(x => x.Team.TeamName == team || team == null)
                .OrderBy(x => x.TeamID)
                .ToList(); 

            return View(bowlers);
        }

        //public IActionResult Index()
        //{
        //    List<Team> teams = _repo.Teams.ToList();

        //    List<Bowler> bowlers = _repo.Bowlers
        //        .OrderBy(x => x.TeamId)
        //        .ToList();
        //    return View(bowlers);
        //}

        // Add a Bowler
        [HttpGet]
        public IActionResult BowlerForm()
        {
            ViewBag.Teams = _repo.Teams.ToList();

            return View(); 
        }

        [HttpPost]
        public IActionResult BowlerForm(Bowler b)
        {
            if (ModelState.IsValid)
            {
                _repo.Add(b);
                _repo.SaveChanges();

                return View("Index", b); //potential take out the b
            }
            else // If Invalid 
            {
                ViewBag.Teams = _repo.Teams.ToList();

                return View();
            }
        }

        // Edit a Bowler
        [HttpGet]
        public IActionResult Edit(int bowlerid)
        {
            ViewBag.Bowlers = _repo.Bowlers.ToList();

            var bowler = _repo.Bowlers.Single(b => b.BowlerID == bowlerid);

            return View("BowlerForm", bowler);
        }

        [HttpPost]
        public IActionResult Edit(Bowler b)
        {
            _repo.Update(b);
            _repo.SaveChanges();

            return RedirectToAction("Index");
        }

        //var someData = context.Bowlers.Include(x => "Team").ToList();
        //return View(someData); (referring to whatever isi in the context file)

        // Delete a Bowler
        [HttpGet]
        public IActionResult Delete(int bowlerid)
        {
            var bowler = _repo.Bowlers.Single(b => b.BowlerID == bowlerid);

            return View(bowler); 
        }

        [HttpPost]
        public IActionResult Delete(Bowler b)
        {
            _repo.Update(b);
            _repo.SaveChanges(); 

            return RedirectToAction("Index");

        }
    }
}

BowlingLeague/Views/Home/BowlerForm.cshtml
@{
    ViewData["Title"] = "Bowler Form";
}

@model BowlingLeague.Models.Bowler

<style>
    .form-element label {
        display: inline-block;
        width: 150px;
    }
</style>

<div>
    <h1>Add a Bowler</h1>

    <form method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="hidden" id="BowlerID" asp-for="BowlerID" />

        <div class="form-element">
            <label asp-for="BowlerFirstName">First Name</label>
            <input asp-for="BowlerFirstName" />
            <br />
        </div>
        <br />

        <div class="form-element">
            <label asp-for="BowlerMiddleInit">Middle Initial</label>
            <input asp-for="BowlerMiddleInit" />
            <br />
        </div>
        <br />


        <div class="form-element">
            <label asp-for="BowlerLastName">Last Name</label>
            <input asp-for="BowlerLastName" />
            <br />
        </div>
        <br />

        <div class="form-element">
            <label asp-for="BowlerAddress">Address</label>
            <input asp-for="BowlerAddress" />
            <br />
        </div>
        <br />

        <div class="form-element">
            <label asp-for="BowlerCity">City</label>
            <input asp-for="BowlerCity" />
            <br />
        </div>
        <br />

        <div class="form-element">
            <label asp-for="BowlerState">State</label>
            <input asp-for="BowlerState" />
            <br />
        </div>
        <br />

        <div class="form-element">
            <label asp-for="BowlerZip">Zip</label>
            <input asp-for="BowlerZip" />
            <br />
        </div>
        <br />

        <div class="form-element">
            <label asp-for="BowlerPhoneNumber">Phone Number</label>
            <input asp-for="BowlerPhoneNumber" />
            <br />
        </div>
        <br />

        <div class="form-element">
            <label asp-for="TeamID">Team</label>
            <select asp-for="TeamID">
                @foreach (Team t in ViewBag.Teams)
                {
                    <option value="@t.TeamID">@t.TeamName</option>
                }
            </select><br />
        </div>
        <br />

        <button class="btn btn-primary" type="submit">Add Bowler</button>

    </form>
</div>

BowlingLeague/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Bowler>

@*@Model.Team...*@

<h1>Bowlers</h1>
<a class="btn btn-primary" asp-area="" asp-controller="Home" asp-action="BowlerForm">Add Bowler</a>

<div class="line">

    <table class="table table-bordered table-striped">
        <thead class="font-weight-bold">
            <tr>
                <td>First Name</td>
                <td>Middle Initial</td>
                <td>Last Name</td>
                <td>Address</td>
                <td>City</td>
                <td>State</td>
                <td>Zip</td>
                <td>Phone Number</td>
            </tr>
        </thead>

        <tbody>
            @foreach (var b in Model)
            {
            <tr>
                <td>@b.BowlerFirstName</td>
                <td>@b.BowlerMiddleInit</td>
                <td>@b.BowlerLastName</td>
                <td>@b.BowlerAddress</td>
                <td>@b.BowlerCity</td>
                <td>@b.BowlerState</td>
                <td>@b.BowlerZip</td>
                <td>@b.BowlerPhoneNumber</td>

                <td><a class="btn btn-warning" asp-controller="Home" asp-action="Edit" asp-route-id="@b.BowlerID">Edit</a></td>
                <td><a class="btn btn-danger" asp-controller="Home" asp-action="Delete" asp-route-id="@b.BowlerID">Delete</a></td>
            </tr>
            }
        </tbody>
    </table>
</div>

BowlingLeague/Views/Shared/Components/Teams/Default.cshtml
@{
}

@model IEnumerable<string> 

<div class="d-grid gap-2">
    <h1>Teams</h1>
    <a asp-controller="Home" asp-action="Index" asp-route-team="" class="btn btn-outline-secondary">Home</a>
    <br />


    @foreach (string t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-team="@t" 
           class="btn @(ViewBag.SelectedTeam == t ? "btn-primary" : "btn-outline-secondary")">@t</a>
        <br />
    }
</div>

BowlingLeague/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BowlingLeague</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BowlingLeague</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="BowlerForm">Add Bowler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="row m-1 p-1">
        <div id="teams" class="col-3">
            <vc:teams></vc:teams>
        </div>

        <div class="col-9">
            @RenderBody()
        </div>
    </div>
    @*<div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>*@

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BowlingLeague
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>